apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-app
  labels:
    app: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda
  template:
    metadata:
      labels:
        app: keda
    spec:
      containers:
      - name: keda
        image: localhost:5000/keda
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: keda-service
spec:
  selector:
    app: keda
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: keda-grpc
spec:
  selector:
    app: keda
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keda-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /keda(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: keda-service
            port:
              number: 8000